format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$jobs\
$cmd_duration\
$line_break\
$character"""

# Inserts a blank line between shell prompts
add_newline = false

[username]
disabled = false
show_always = true
format = '\[[$user]($style)@' 
style_user = 'bold #2AA1B3'
style_root = 'bold #E45B4F'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname]($style)\] '
trim_at = '.companyname.com'
disabled = false
style = 'bold #1AA1B2'

[directory]
style = 'bold #4078f2'

[character]
success_symbol = '[❯](bold #2AA1b3)'
error_symbol = '[❯](bold #E45B4F)'
vicmd_symbol = '[❮](bold blue)'

# [character]
# success_symbol = '[](bold #98C6EC)'
# error_symbol = '[](bold red)'
# vicmd_symbol = '[<](bold blue)' # not working

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_metrics]
added_style = 'bold #2b8c63'
deleted_style = 'bold #E45B4F'
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[fill]
symbol = " "

[jobs]
symbol = "+ "
style = "bold #2b8c63"

[package]
disabled = true
