format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration $jobs $time\
$line_break\
$character"""

# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = '[](bold cyan)'
error_symbol = '[](bold red)'
vicmd_symbol = '[<](bold blue)' # not working

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[fill]
symbol = " "

[package]
disabled = true
